<a href="https://colab.research.google.com/github/Amonstarr/Twitter-Classification-Using-Indobert/blob/main/Indobert_preprocessing_engine_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
!pip install sastrawi

Collecting sastrawi
  Downloading Sastrawi-1.0.1-py2.py3-none-any.whl.metadata (909 bytes)
Downloading Sastrawi-1.0.1-py2.py3-none-any.whl (209 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 209.7/209.7 kB 8.0 MB/s eta 0:00:00
Installing collected packages: sastrawi
Successfully installed sastrawi-1.0.1

In [ ]:
import pandas as pd
import re
import string
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Satria Data/dataset_penyisihan_bdc_2024 (2).csv", sep=';')
df.head()

                                                text             label
0  Kunjungan Prabowo ini untuk meresmikan dan men...  Sumber Daya Alam
1  RT Anies dapat tepuk tangan meriah saat jadi R...           Politik
2  @CIqXqwGAT04tMtx4OCATxjoVq7vv/Y8HeYaIOgMFg8Y= ...         Demografi
3  RT @L3R8XFBw3WGbxRPSj0/0hHZTbqVGX7qtfwRg9zmhK7...           Politik
4  Anies Baswedan Harap ASN termasuk TNI dan Polr...           Politik

In [ ]:
df_test = pd.read_csv("/content/drive/MyDrive/Satria Data/dataset_unlabeled_penyisihan_bdc_2024.csv", sep=';')
df_test.head()

    IDText                                               Text
0  TXT0001  Lu mau org2 pro-demokrasi di negara ini bisa p...
1  TXT0002  Prabowo ditanya soal hutang luar negeri dia me...
2  TXT0003  kiki_daliyo  Ganjar Pranowo itulah beliau soso...
3  TXT0004  @kumparan Prabowo Gibran yang bisa melakukan i...
4  TXT0005  @sniperruben45 @uda_zulhendra @ainunnajib Lah ...

In [ ]:
KOLOM_LABEL= "label" #@param {type:"string"}
print(df[KOLOM_LABEL].unique())
# print(df_test[KOLOM_LABEL].unique())

['Sumber Daya Alam' 'Politik' 'Demografi' 'Pertahanan dan Keamanan'
 'Ideologi' 'Ekonomi' 'Sosial Budaya' 'Geografi']

# Preprocessing

In [ ]:
class DataCleaning:
  # Initialization
  factory     = StemmerFactory()
  stemmer     = factory.create_stemmer()
  kamus_alay1 = pd.read_csv('https://raw.githubusercontent.com/fendiirfan/Kamus-Alay/main/Kamus-Alay.csv') # Corrected URL
  kamus_alay1 = kamus_alay1.set_index('kataAlay')
  kamus_alay2 = pd.read_csv('https://raw.githubusercontent.com/nasalsabila/kamus-alay/master/colloquial-indonesian-lexicon.csv')
  kamus_alay2 = kamus_alay2.filter(['slang', 'formal'], axis=1)
  kamus_alay2 = kamus_alay2.drop_duplicates(subset=['slang'], keep='first')
  kamus_alay2 = kamus_alay2.set_index('slang')
  stopword1   = list(pd.read_csv('https://raw.githubusercontent.com/datascienceid/stopwords-bahasa-indonesia/master/stopwords_id_satya.txt', header = None)[0])
  custom_word = []

  @classmethod
  def CleanDataFrame(cls, df, col_name, label_name, jum_minimum=None, minimum_kata=0, label_mapping=None, dropna=False):

    final_list_clean = []
    final_list_kotor = []
    final_label = []

    if jum_minimum == None: jum_minimum = len(df)
    if len(df) < jum_minimum: raise "Jumlah Data Yang Diinginkan melebihi Data yang Ada"
    i = 0
    current = 0

    while i < len(df):
      current_kalimat = df.loc[i][col_name]
      current_label = df.loc[i][label_name]

      clean_kalimat = cls.__cleanSentence__(current_kalimat)
      if type(clean_kalimat) != str or clean_kalimat == None or clean_kalimat == "":
        print("Ditemukan string kosong setelah di preprocessed pada kalimat: ", current_kalimat)
        clean_kalimat = "NaN"
      if (len(clean_kalimat.split(' ')) >= minimum_kata):
        final_list_clean.append(str(clean_kalimat))
        final_list_kotor.append(str(current_kalimat))
        if label_mapping != None:
          final_label.append(label_mapping[current_label])
        else:
          final_label.append(current_label)
        current += 1

        if current % 10 == 0:
          print("Memproses {} data".format(current))

      if current == jum_minimum:
        break

      i += 1

    data = {
        'raw': final_list_kotor,
        'processed': final_list_clean,
        'label': final_label
    }

    final_df = pd.DataFrame(data)
    if dropna:
      print("NaN Dropped")
      final_df = final_df.dropna(how='any')

    final_df['processed'] = final_df['processed'].astype(str)
    final_df['raw'] = final_df['raw'].astype(str)
    return final_df

  @classmethod
  def __cleanSentence__(cls, text):
    '''
    Melakukan prapemrosesan pada suatu kalimat dengan menghilangkan formatting pada kalimat,
    menghilangkan stopword pada kalimat, mengganti kata alay yang sudah terdefinisikan, serta
    melakukan stemming kalimat tersebut.
    '''

    # #
    # Cleaning Formatted Text Link And Tag (@username) using Regex
    # #
    text = re.sub(r'http\S+', '', text)
    text = re.sub(r'(@\w+|#\w+)','',text)

    #will replace the html characters with " "
    text = re.sub('<.*?>', '', text)

    temp_text = list(text)
    for i in range(len(temp_text)):
      if temp_text[i] in string.punctuation:
        temp_text[i] = " "

    text = ''.join(temp_text)

    #will consider only alphabets
    text = re.sub('[^a-zA-Z]',' ',text)
    #will replace newline with space
    text = re.sub("\n"," ",text)
    #will convert to lower case
    text = text.lower()
    # will replace a word
    text = re.sub(r"(username|user|url|rt|xf|fx|xe|xa)\s|\s(user|url|rt|xf|fx|xe|xa)","",text)
    # will repalce repated char
    text = re.sub(r'(\w)(\1{2,})', r"\1", text)
    # will replace single word
    text = re.sub(r"\b[a-zA-Z]\b","",text)
    # will replace space more than one
    text = re.sub('(s{2,})',' ',text)
    # will join the words
    text=' '.join(text.split())

    text_split = text.split(' ')
    # #
    # Mengganti kata-kata yang tidak baku
    # aku gapakai try catch lagi, lebih simple malah ini
    # #
    for i in range(len(text_split)):
      if text_split[i] in cls.kamus_alay1.index:
        text_split[i] = cls.kamus_alay1.loc[text_split[i]]['kataBaik']
      elif text_split[i] in cls.kamus_alay2.index:
        text_split[i] = cls.kamus_alay2.loc[text_split[i]]['formal']

    # #
    # Stemming
    # #
    stemmed_text = cls.stemmer.stem(text)

    # #
    # Removing Stopwords and custom word
    # #
    temp_text_split = []
    for i in range(len(text_split)):
      if (text_split[i] not in cls.stopword1) and (text_split[i] not in cls.custom_word) and (type(text_split[i]) == str):
        temp_text_split.append(text_split[i])

    # Memastikan saja
    if len(temp_text_split) == 0:
      return ""
    else:
      final_text = ' '.join(temp_text_split)

    return final_text

Non-Stopword

In [ ]:
# class DataCleaning:
#   # Initialization
#   factory     = StemmerFactory()
#   stemmer     = factory.create_stemmer()
#   kamus_alay1 = pd.read_csv('https://raw.githubusercontent.com/fendiirfan/Kamus-Alay/main/Kamus-Alay.csv') # Corrected URL
#   kamus_alay1 = kamus_alay1.set_index('kataAlay')
#   kamus_alay2 = pd.read_csv('https://raw.githubusercontent.com/nasalsabila/kamus-alay/master/colloquial-indonesian-lexicon.csv')
#   kamus_alay2 = kamus_alay2.filter(['slang', 'formal'], axis=1)
#   kamus_alay2 = kamus_alay2.drop_duplicates(subset=['slang'], keep='first')
#   kamus_alay2 = kamus_alay2.set_index('slang')
#   stopword1   = list(pd.read_csv('https://raw.githubusercontent.com/datascienceid/stopwords-bahasa-indonesia/master/stopwords_id_satya.txt', header = None)[0])
#   custom_word = []

#   @classmethod
#   def CleanDataFrame(cls, df, col_name, label_name, jum_minimum=None, minimum_kata=0, label_mapping=None, dropna=False):

#     final_list_clean = []
#     final_list_kotor = []
#     final_label = []

#     if jum_minimum == None: jum_minimum = len(df)
#     if len(df) < jum_minimum: raise "Jumlah Data Yang Diinginkan melebihi Data yang Ada"
#     i = 0
#     current = 0

#     while i < len(df):
#       current_kalimat = df.loc[i][col_name]
#       current_label = df.loc[i][label_name]

#       clean_kalimat = cls.__cleanSentence__(current_kalimat)
#       if type(clean_kalimat) != str or clean_kalimat == None or clean_kalimat == "":
#         print("Ditemukan string kosong setelah di preprocessed pada kalimat: ", current_kalimat)
#         clean_kalimat = "NaN"
#       if (len(clean_kalimat.split(' ')) >= minimum_kata):
#         final_list_clean.append(str(clean_kalimat))
#         final_list_kotor.append(str(current_kalimat))
#         if label_mapping != None:
#           final_label.append(label_mapping[current_label])
#         else:
#           final_label.append(current_label)
#         current += 1

#         if current % 10 == 0:
#           print("Memproses {} data".format(current))

#       if current == jum_minimum:
#         break

#       i += 1

#     data = {
#         'raw': final_list_kotor,
#         'processed': final_list_clean,
#         'label': final_label
#     }

#     final_df = pd.DataFrame(data)
#     if dropna:
#       print("NaN Dropped")
#       final_df = final_df.dropna(how='any')

#     final_df['processed'] = final_df['processed'].astype(str)
#     final_df['raw'] = final_df['raw'].astype(str)
#     return final_df

#   @classmethod
#   def __cleanSentence__(cls, text):
#     '''
#     Melakukan prapemrosesan pada suatu kalimat dengan menghilangkan formatting pada kalimat,
#     menghilangkan stopword pada kalimat, mengganti kata alay yang sudah terdefinisikan, serta
#     melakukan stemming kalimat tersebut.
#     '''

#     # #
#     # Cleaning Formatted Text Link And Tag (@username) using Regex
#     # #
#     text = re.sub(r'http\S+', '', text)
#     text = re.sub('(@\w+|#\w+)','',text)

#     #will replace the html characters with " "
#     text = re.sub('<.*?>', '', text)

#     temp_text = list(text)
#     for i in range(len(temp_text)):
#       if temp_text[i] in string.punctuation:
#         temp_text[i] = " "

#     text = ''.join(temp_text)

#     #will consider only alphabets
#     text = re.sub('[^a-zA-Z]',' ',text)
#     #will replace newline with space
#     text = re.sub("\n"," ",text)
#     #will convert to lower case
#     text = text.lower()
#     # will replace a word
#     text = re.sub("(username|user|url|rt|xf|fx|xe|xa)\s|\s(user|url|rt|xf|fx|xe|xa)","",text)
#     # will repalce repated char
#     text = re.sub(r'(\w)(\1{2,})', r"\1", text)
#     # will replace single word
#     text = re.sub(r"\b[a-zA-Z]\b","",text)
#     # will replace space more than one
#     text = re.sub('(s{2,})',' ',text)
#     # will join the words
#     text=' '.join(text.split())

#     text_split = text.split(' ')
#     # #
#     # Mengganti kata-kata yang tidak baku
#     # aku gapakai try catch lagi, lebih simple malah ini
#     # #
#     for i in range(len(text_split)):
#       if text_split[i] in cls.kamus_alay1.index:
#         text_split[i] = cls.kamus_alay1.loc[text_split[i]]['kataBaik']
#       elif text_split[i] in cls.kamus_alay2.index:
#         text_split[i] = cls.kamus_alay2.loc[text_split[i]]['formal']

#     # #
#     # Stemming
#     # #
#     stemmed_text = cls.stemmer.stem(text)

#     # #
#     # Removing Stopwords and custom word
#     # #
#     temp_text_split = []
#     for i in range(len(text_split)):
#       if (type(text_split[i]) == str):
#         temp_text_split.append(text_split[i])

#     # Memastikan saja
#     if len(temp_text_split) == 0:
#       return ""
#     else:
#       final_text = ' '.join(temp_text_split)

#     return final_text

In [ ]:
unique_labels = df[KOLOM_LABEL].unique()
label_mapping = {label: i for i, label in enumerate(unique_labels)}

print("Generated label_mapping:")
print(label_mapping)

Generated label_mapping:
{'Sumber Daya Alam': 0, 'Politik': 1, 'Demografi': 2, 'Pertahanan dan Keamanan': 3, 'Ideologi': 4, 'Ekonomi': 5, 'Sosial Budaya': 6, 'Geografi': 7}

In [ ]:
df = DataCleaning.CleanDataFrame(df, 'text', 'label', None, 2, label_mapping, dropna=True)
print(len(df))

Memproses 10 data
Memproses 20 data
Memproses 30 data
Memproses 40 data
Memproses 50 data
Memproses 60 data
Memproses 70 data
Memproses 80 data
Memproses 90 data
Memproses 100 data
Memproses 110 data
Memproses 120 data
Memproses 130 data
Memproses 140 data
Memproses 150 data
Memproses 160 data
Memproses 170 data
Memproses 180 data
Memproses 190 data
Memproses 200 data
Memproses 210 data
Memproses 220 data
Memproses 230 data
Memproses 240 data
Memproses 250 data
Memproses 260 data
Memproses 270 data
Memproses 280 data
Memproses 290 data
Memproses 300 data
Memproses 310 data
Memproses 320 data
Memproses 330 data
Memproses 340 data
Memproses 350 data
Memproses 360 data
Memproses 370 data
Memproses 380 data
Memproses 390 data
Memproses 400 data
Memproses 410 data
Memproses 420 data
Memproses 430 data
Memproses 440 data
Memproses 450 data
Memproses 460 data
Memproses 470 data
Memproses 480 data
Memproses 490 data
Memproses 500 data
Memproses 510 data
Memproses 520 data
Memproses 530 data
Memproses 540 data
Memproses 550 data
Memproses 560 data
Memproses 570 data
Memproses 580 data
Memproses 590 data
Memproses 600 data
Memproses 610 data
Memproses 620 data
Memproses 630 data
Memproses 640 data
Memproses 650 data
Memproses 660 data
Memproses 670 data
Memproses 680 data
Memproses 690 data
Memproses 700 data
Memproses 710 data
Memproses 720 data
Memproses 730 data
Memproses 740 data
Memproses 750 data
Memproses 760 data
Memproses 770 data
Memproses 780 data
Memproses 790 data
Memproses 800 data
Memproses 810 data
Memproses 820 data
Memproses 830 data
Memproses 840 data
Memproses 850 data
Memproses 860 data
Memproses 870 data
Memproses 880 data
Memproses 890 data
Memproses 900 data
Memproses 910 data
Memproses 920 data
Memproses 930 data
Memproses 940 data
Memproses 950 data
Memproses 960 data
Memproses 970 data
Memproses 980 data
Memproses 990 data
Memproses 1000 data
Memproses 1010 data
Memproses 1020 data
Memproses 1030 data
Memproses 1040 data
Memproses 1050 data
Memproses 1060 data
Memproses 1070 data
Memproses 1080 data
Memproses 1090 data
Memproses 1100 data
Memproses 1110 data
Memproses 1120 data
Memproses 1130 data
Memproses 1140 data
Memproses 1150 data
Memproses 1160 data
Memproses 1170 data
Memproses 1180 data
Memproses 1190 data
Memproses 1200 data
Memproses 1210 data
Memproses 1220 data
Memproses 1230 data
Memproses 1240 data
Memproses 1250 data
Memproses 1260 data
Memproses 1270 data
Memproses 1280 data
Memproses 1290 data
Memproses 1300 data
Memproses 1310 data
Memproses 1320 data
Memproses 1330 data
Memproses 1340 data
Memproses 1350 data
Memproses 1360 data
Memproses 1370 data
Memproses 1380 data
Memproses 1390 data
Memproses 1400 data
Memproses 1410 data
Memproses 1420 data
Memproses 1430 data
Memproses 1440 data
Memproses 1450 data
Memproses 1460 data
Memproses 1470 data
Memproses 1480 data
Memproses 1490 data
Memproses 1500 data
Memproses 1510 data
Memproses 1520 data
Memproses 1530 data
Memproses 1540 data
Memproses 1550 data
Memproses 1560 data
Memproses 1570 data
Memproses 1580 data
Memproses 1590 data
Memproses 1600 data
Memproses 1610 data
Memproses 1620 data
Memproses 1630 data
Memproses 1640 data
Memproses 1650 data
Memproses 1660 data
Memproses 1670 data
Memproses 1680 data
Memproses 1690 data
Memproses 1700 data
Memproses 1710 data
Memproses 1720 data
Memproses 1730 data
Memproses 1740 data
Memproses 1750 data
Memproses 1760 data
Memproses 1770 data
Memproses 1780 data
Memproses 1790 data
Memproses 1800 data
Memproses 1810 data
Memproses 1820 data
Memproses 1830 data
Memproses 1840 data
Memproses 1850 data
Memproses 1860 data
Memproses 1870 data
Memproses 1880 data
Memproses 1890 data
Memproses 1900 data
Memproses 1910 data
Memproses 1920 data
Memproses 1930 data
Memproses 1940 data
Memproses 1950 data
Memproses 1960 data
Memproses 1970 data
Memproses 1980 data
Memproses 1990 data
Memproses 2000 data
Memproses 2010 data
Memproses 2020 data
Memproses 2030 data
Memproses 2040 data
Memproses 2050 data
Memproses 2060 data
Memproses 2070 data
Memproses 2080 data
Memproses 2090 data
Memproses 2100 data
Memproses 2110 data
Memproses 2120 data
Memproses 2130 data
Memproses 2140 data
Memproses 2150 data
Memproses 2160 data
Memproses 2170 data
Memproses 2180 data
Memproses 2190 data
Memproses 2200 data
Memproses 2210 data
Memproses 2220 data
Memproses 2230 data
Memproses 2240 data
Memproses 2250 data
Memproses 2260 data
Memproses 2270 data
Memproses 2280 data
Memproses 2290 data
Memproses 2300 data
Memproses 2310 data
Memproses 2320 data
Memproses 2330 data
Memproses 2340 data
Memproses 2350 data
Memproses 2360 data
Memproses 2370 data
Memproses 2380 data
Memproses 2390 data
Memproses 2400 data
Memproses 2410 data
Memproses 2420 data
Memproses 2430 data
Memproses 2440 data
Memproses 2450 data
Memproses 2460 data
Memproses 2470 data
Memproses 2480 data
Memproses 2490 data
Memproses 2500 data
Memproses 2510 data
Memproses 2520 data
Memproses 2530 data
Memproses 2540 data
Memproses 2550 data
Memproses 2560 data
Memproses 2570 data
Memproses 2580 data
Memproses 2590 data
Memproses 2600 data
Memproses 2610 data
Memproses 2620 data
Memproses 2630 data
Memproses 2640 data
Memproses 2650 data
Memproses 2660 data
Memproses 2670 data
Memproses 2680 data
Memproses 2690 data
Memproses 2700 data
Memproses 2710 data
Memproses 2720 data
Memproses 2730 data
Memproses 2740 data
Memproses 2750 data
Memproses 2760 data
Memproses 2770 data
Memproses 2780 data
Memproses 2790 data
Memproses 2800 data
Memproses 2810 data
Memproses 2820 data
Memproses 2830 data
Memproses 2840 data
Memproses 2850 data
Memproses 2860 data
Memproses 2870 data
Memproses 2880 data
Memproses 2890 data
Memproses 2900 data
Memproses 2910 data
Memproses 2920 data
Memproses 2930 data
Memproses 2940 data
Memproses 2950 data
Memproses 2960 data
Memproses 2970 data
Memproses 2980 data
Memproses 2990 data
Memproses 3000 data
Memproses 3010 data
Memproses 3020 data
Memproses 3030 data
Memproses 3040 data
Memproses 3050 data
Memproses 3060 data
Memproses 3070 data
Memproses 3080 data
Memproses 3090 data
Memproses 3100 data
Memproses 3110 data
Memproses 3120 data
Memproses 3130 data
Memproses 3140 data
Memproses 3150 data
Memproses 3160 data
Memproses 3170 data
Memproses 3180 data
Memproses 3190 data
Memproses 3200 data
Memproses 3210 data
Memproses 3220 data
Memproses 3230 data
Memproses 3240 data
Memproses 3250 data
Memproses 3260 data
Memproses 3270 data
Memproses 3280 data
Memproses 3290 data
Memproses 3300 data
Memproses 3310 data
Memproses 3320 data
Memproses 3330 data
Memproses 3340 data
Memproses 3350 data
Memproses 3360 data
Memproses 3370 data
Memproses 3380 data
Memproses 3390 data
Memproses 3400 data
Memproses 3410 data
Memproses 3420 data
Memproses 3430 data
Memproses 3440 data
Memproses 3450 data
Memproses 3460 data
Memproses 3470 data
Memproses 3480 data
Memproses 3490 data
Memproses 3500 data
Memproses 3510 data
Memproses 3520 data
Memproses 3530 data
Memproses 3540 data
Memproses 3550 data
Memproses 3560 data
Memproses 3570 data
Memproses 3580 data
Memproses 3590 data
Memproses 3600 data
Memproses 3610 data
Memproses 3620 data
Memproses 3630 data
Memproses 3640 data
Memproses 3650 data
Memproses 3660 data
Memproses 3670 data
Memproses 3680 data
Memproses 3690 data
Memproses 3700 data
Memproses 3710 data
Memproses 3720 data
Memproses 3730 data
Memproses 3740 data
Memproses 3750 data
Memproses 3760 data
Memproses 3770 data
Memproses 3780 data
Memproses 3790 data
Memproses 3800 data
Memproses 3810 data
Memproses 3820 data
Memproses 3830 data
Memproses 3840 data
Memproses 3850 data
Memproses 3860 data
Memproses 3870 data
Memproses 3880 data
Memproses 3890 data
Memproses 3900 data
Memproses 3910 data
Memproses 3920 data
Memproses 3930 data
Memproses 3940 data
Memproses 3950 data
Memproses 3960 data
Memproses 3970 data
Memproses 3980 data
Memproses 3990 data
Memproses 4000 data
Memproses 4010 data
Memproses 4020 data
Memproses 4030 data
Memproses 4040 data
Memproses 4050 data
Memproses 4060 data
Memproses 4070 data
Memproses 4080 data
Memproses 4090 data
Memproses 4100 data
Memproses 4110 data
Memproses 4120 data
Memproses 4130 data
Memproses 4140 data
Memproses 4150 data
Memproses 4160 data
Memproses 4170 data
Memproses 4180 data
Memproses 4190 data
Memproses 4200 data
Memproses 4210 data
Memproses 4220 data
Memproses 4230 data
Memproses 4240 data
Memproses 4250 data
Memproses 4260 data
Memproses 4270 data
Memproses 4280 data
Memproses 4290 data
Memproses 4300 data
Memproses 4310 data
Memproses 4320 data
Memproses 4330 data
Memproses 4340 data
Memproses 4350 data
Memproses 4360 data
Memproses 4370 data
Memproses 4380 data
Memproses 4390 data
Memproses 4400 data
Memproses 4410 data
Memproses 4420 data
Memproses 4430 data
Memproses 4440 data
Memproses 4450 data
Memproses 4460 data
Memproses 4470 data
Memproses 4480 data
Memproses 4490 data
Memproses 4500 data
Memproses 4510 data
Memproses 4520 data
Memproses 4530 data
Memproses 4540 data
Memproses 4550 data
Memproses 4560 data
Memproses 4570 data
Memproses 4580 data
Memproses 4590 data
Memproses 4600 data
Memproses 4610 data
Memproses 4620 data
Memproses 4630 data
Memproses 4640 data
Memproses 4650 data
Memproses 4660 data
Memproses 4670 data
Memproses 4680 data
Memproses 4690 data
Memproses 4700 data
Memproses 4710 data
Memproses 4720 data
Memproses 4730 data
Memproses 4740 data
Memproses 4750 data
Memproses 4760 data
Memproses 4770 data
Memproses 4780 data
Memproses 4790 data
Memproses 4800 data
Memproses 4810 data
Memproses 4820 data
Memproses 4830 data
Memproses 4840 data
Memproses 4850 data
Memproses 4860 data
Memproses 4870 data
Memproses 4880 data
Memproses 4890 data
Memproses 4900 data
Memproses 4910 data
Memproses 4920 data
Memproses 4930 data
Memproses 4940 data
Memproses 4950 data
Memproses 4960 data
Memproses 4970 data
Memproses 4980 data
Memproses 4990 data
Memproses 5000 data
NaN Dropped
5000

In [ ]:
# Jangan Ditimpa Data Aslinya
df.to_csv(
    '/content/drive/MyDrive/Satria Data/dataset_penyisihan_bdc_2024_clean.csv',
    index=False,
    encoding='utf-8',
    na_rep=""
)
df[df['processed'] == "NaN"]

Empty DataFrame
Columns: [raw, processed, label]
Index: []

In [ ]:
df_test['processed'] = df_test['Text'].apply(
    DataCleaning.__cleanSentence__
)

#Jangan Ditimpa Data Aslinya
df_test.to_csv('/content/drive/MyDrive/Satria Data/datatest_penyisihan_bdc_2024_clean.csv', index=False)